### ISSUE TITLE
permissions for audituser unclear

### ISSUE THREAD

**Issue by whysthatso** [prometheus-pve/prometheus-pve-exporter#100]
first of: i can run the exporter successfully from a secondary machine against my single proxmox node using the root@pam user account, so i confirmed the exporter (using docker) works for me.

i've created a pve user through the gui: metrics@pve
i then added the the following roles for the list of paths:
![Screenshot_20211203_233757](https://user-images.githubusercontent.com/1685114/144676128-edd6bb6e-82e1-40ed-b66d-eef01e79164f.png)
 
however, i am getting an exception with a 403. i cannot deduce what role/permission i seem to be missing. 

can anybody help?

```
Exception thrown while rendering view
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pve_exporter/http.py", line 96, in view
    return view_registry[endpoint](**params)
  File "/usr/lib/python3.8/site-packages/pve_exporter/http.py", line 38, in on_pve
    output = collect_pve(self._config[module], target, self._collectors)
  File "/usr/lib/python3.8/site-packages/pve_exporter/collector.py", line 332, in collect_pve
    return generate_latest(registry)
  File "/usr/lib/python3.8/site-packages/prometheus_client/exposition.py", line 107, in generate_latest
    for metric in registry.collect():
  File "/usr/lib/python3.8/site-packages/prometheus_client/registry.py", line 83, in collect
    for metric in collector.collect():
  File "/usr/lib/python3.8/site-packages/pve_exporter/collector.py", line 45, in collect
    for entry in self._pve.cluster.status.get():
  File "/usr/lib/python3.8/site-packages/proxmoxer/core.py", line 105, in get
    return self(args)._request("GET", params=params)
  File "/usr/lib/python3.8/site-packages/proxmoxer/core.py", line 90, in _request
    raise ResourceException("{0} {1}: {2} - {3}".format(
proxmoxer.core.ResourceException: 403 Forbidden: Permission check failed (/, Sys.Audit) - b'{"data":null}'
```

**Comment by znerol** [comment]
The user needs access to the following resources: `/cluster` and `/version`. If the `config` collector is enabled (which I do not recommend due to its inherent performance issues), then it also needs access to `/nodes`.

**Comment by whysthatso** [comment]
hm, curious. /cluster and /version are not resource paths i have available for choice. when entering these explicitly in 'User: Add Permission' dialogue, i get:

```
Parameter verification failed. (400)

path: invalid ACL path '/cluster'
```
 i have these:
```
/
/access
/access/groups
/access/realm
/nodes
/nodes/node-1
/pool
/storage
/storage/guests
/storage/local
/vms
/vms/1
```

however, it turns out when i only assign `/` - so presumably everything - it works. is that proper?

**Comment by znerol** [comment]
> however, it turns out when i only assign / - so presumably everything - it works. is that proper?
Yes. In fact I never attempted to restrict the exporter account to resources.

You observed an interesting thing though. Might be worthwhile to dig into the privilege separation mechanisms in PVE and see whether there are technical reasons for the absence of `/cluster` from the path restriction options.

**Comment by whysthatso** [comment]
maybe because of the fact that i am running a single node setup?

would you mind a pr with a small doc change explicitly stating this?

**Comment by znerol** [comment]
> maybe because of the fact that i am running a single node setup?

No, I just verified that the `/cluster` path is not visible on clusters neither. Thus, the permissions do not map 1:1 to API resources. In fact the `path` in permissions rather maps to some kind of organization hierarchy. The idea seems to be that cluster administrators add pools (groups of VMs, storage, etc) and then delegate access to those pools to departments / clients.

> would you mind me putting up a pr with a small doc change explicitly stating this kind of needed permission configuration?

Sure. Currently the README contains the following sentence:

> For security reasons it is essential to add a user with read-only access (PVEAuditor role) for the purpose of metrics collection.

If anybody could come-up with better wording, then please go ahead.

**Comment by znerol** [comment]
Merged, thanks.
