### ISSUE TITLE
Confusing Wiki Documentation for Systemd Install

### ISSUE THREAD

**Issue by Kashalls** [prometheus-pve/prometheus-pve-exporter#107]
So, I was recently adding this to my nodes for monitoring purposes. I followed this wiki which is pretty easy to understand if you know what you're doing. However, I noticed that we run the service under the prometheus user, but we create it as a pve user account, so the prometheus user doesn't exist in the PAM namespace.

Can I get some clarification about this?
https://github.com/prometheus-pve/prometheus-pve-exporter/wiki/PVE-Exporter-on-Proxmox-VE-Node-in-a-venv

**Comment by znerol** [comment]
Thanks for the report. I see that the documentation could be confusing. The wiki page assumes that there is a `prometheus` system user (referenced in the systemd unit), but it does not describe how to create it. Also it assumes that there is a `prometheus` user in the `pve` realm (referenced in the config file), but again fails to explain how to create it.
