### ISSUE TITLE
Python can't find config file

### ISSUE THREAD

**Issue by D13410N3** [prometheus-pve/prometheus-pve-exporter#110]
Hello
I'm trying to execute this:

```
docker run --name prometheus-pve-exporter -d -p 0.0.0.0:9221:9221 -v /etc/pve.yml:/etc/pve.yml prompve/prometheus-pve-exporter
```
Nothing happens
But when I try to start container again:
```
docker run prompve/prometheus-pve-exporter
```
I'm getting this error:
```
Traceback (most recent call last):
  File "/usr/bin/pve_exporter", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/pve_exporter/cli.py", line 107, in main
    with open(params.config) as handle:
```

File `/etc/pve.yml` exists
Docker version is `20.10.5+dfsg1`

**Comment by znerol** [comment]
`docker run` is the wrong command to start an existing container. Use `docker start`.

**Comment by D13410N3** [comment]
Same error.
Seems like it's easier to use "no-docker" conception.

Thanks

**Comment by znerol** [comment]
You could also recreate the container on every start in combination with the `--rm` flag:

```
docker run --name prometheus-pve-exporter -d -p 0.0.0.0:9221:9221 -v /etc/pve.yml:/etc/pve.yml --rm prompve/prometheus-pve-exporter
```

If you additionally use `--pull=always`, the image will be kept up-to-date as well.

**Comment by Dan-Sun** [comment]
Hi

Just testing your exporter but I can't get it to work as well.

It can't find the config file.

`docker run --name prometheus-pve-exporter -d -p 0.0.0.0:9221:9221 -v /etc/prometheus/pve.yml:/etc/pve.yml --rm prompve/prometheus-pve-exporter`

`docker run -it --rm prompve/prometheus-pve-exporter --collector.status`
```
Traceback (most recent call last):
  File "/usr/bin/pve_exporter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/pve_exporter/cli.py", line 109, in main
    with open(params.config) as handle:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'pve.yml'```
