### ISSUE TITLE
Support Proxmox behind reverse proxy

### ISSUE THREAD

**Issue by danielr1996** [prometheus-pve/prometheus-pve-exporter#117]
I'm running proxmox behind a reverse proxy so I access it in the browser at proxmox.<mydomain>.de, when I tried to supply that as the ?target parameter python through a bunch of exceptions telling me  proxmox.<mydomain>.de:8006 was not reachable. 

Would it be possible to not assume that an instance is reachable at port 8006 but take the whole ?target parameter as an argument to proxmox api library, this would also be beneficial for proxmox installations that don't run on port 8006

**Comment by jhollowe** [comment]
I haven't looked exactly at how this passes arguments into proxmoxer, but I think you can just add `port: 443` to your `pve.yaml` file and it should work

**Comment by dubyatp** [comment]
I was able to connect to my PVE cluster over my traefik reverse proxy by simply adding `:443` to the end of the domain
