### ISSUE TITLE
Best way to auto start on boot and in background.

### ISSUE THREAD

**Issue by mkono87** [prometheus-pve/prometheus-pve-exporter#126]
The way this is running on proxmox with the pip version is to run the command. What would be the best way to have it auto start as a service?

**Comment by znerol** [comment]
Please take a look into the wiki. Especially [PVE Exporter on Proxmox VE Node in a venv](https://github.com/prometheus-pve/prometheus-pve-exporter/wiki/PVE-Exporter-on-Proxmox-VE-Node-in-a-venv).
