### ISSUE TITLE
500 error when  Prometheus connects to pve endpoint 

### ISSUE THREAD

**Issue by wilddev65** [prometheus-pve/prometheus-pve-exporter#136]
I have setup pve-exporter as mentioned in the readme on my proxmox server but Prometheus only gets the following error:
server returned HTTP status 500 INTERNAL SERVER ERROR

The log from the service has;
Mar 15 17:51:01 pve1 pve_exporter[416221]: requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=8006): Max retries exceeded with url: /api2/json/cluster/status (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
Mar 15 17:51:01 pve1 pve_exporter[416221]: 192.168.1.1 - - [15/Mar/2023 17:51:01] "GET /pve?module=default HTTP/1.1" 500 -

How can I resolve this?

**Comment by znerol** [comment]
>  Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)'))

It looks like this pve instance is operated with a self-signed TLS certificate. I recommend to use Let's Encrypt (or any other trusted certs) for production setup. If this is not an option, the please read through the  _Authentication_ section in the README, and pay special attention to the _Note on verify_ssl and certificate trust store_.
