### ISSUE TITLE
IPV6 Resolution of Proxmox Node DNS name failing when pve-exporter run as a pod on a kubernetes cluster

### ISSUE THREAD

**Issue by wattsap** [prometheus-pve/prometheus-pve-exporter#137]
Hello,

I am interested in running pve-exporter as a pod on a kubernetes cluster.

I have a proxmox node with SSL enabled, and a DNS rewrite setup on my DNS server(Adguardhome) <my-domain-name-rewrite>.

I have configured the cluster coredns with an upstream name server pointed at my DNS server. This is working in other apps to lookup DNS rewrites in adguard - its even working for other prometheus exporters(Unifi-Poller for example).

I have configured a deployment for the pod and am using a configmap to mount pve.yml to the container for auth. 

I have configured a ClusterIP service to expose the deployment to prometheus for scraping - prometheus is running in another namespace on the same cluster.

To test and see that the metrics were flowing I was using kubectl port-forwarding and hitting the endpoint from my desktop, and when I hit the endpoint with 127.0.0.1:9221/pve?target=https://<my-domain-name-rewrite>, I got the below error in the pve-exporter logs:

`  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=8006): Max retries exceeded with url: /api2/json/cluster/status (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0b5ed054b0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
127.0.0.1 - - [17/Mar/2023 04:31:13] "GET /pve?target=https://<my-domain-name-rewrite>t HTTP/1.1" 500 -
`

When I update pve.yml to disable ssl and  hit the endpoint instead with 127.0.0.1:9221/pve?target=192.168.1.65, I am able to load the metrics.

when I exec the pve-exporter pod and run nslookup commands, I get the below output:
`~ $ nslookup <my-domain-name-rewrite>
Server:         10.43.0.10
Address:        10.43.0.10:53

Non-authoritative answer:
<my-domain-name-rewrite>  canonical name = <secondary-cname-rewrite>
Name:   <secondary-cname-rewrite>
Address: 192.168.1.65

** server can't find <my-domain-name-rewrite>: NXDOMAIN
`

It both resolves the IP and returns NXDOMAIN. I believe this is because of IPV6, if I run nslookup with protocol ipv4 flag I get a standard response back:

`~ $ nslookup -q=A <my-domain-name-rewrite>
Server:         10.43.0.10
Address:        10.43.0.10:53

Non-authoritative answer:
<my-domain-name-rewrite>  canonical name = <secondary-cname-rewrite>
Name:   <secondary-cname-rewrite>
Address: 192.168.1.65
`

using the IP of the proxmox node instead of the DNS name does work, and I'm able to successfully use my ClusterIP service in the prometheus scrape configs, so its not a dealbreaker but I'm a little lost on how to further troubleshoot. 

Is this something specific to the IPV6 implementation being used by pve-exporter? Or is this something specific to the way adguardhome responds to IPV6 queries? Could it be something specfic to proxmox IPV6 configuration? I don't know enough about IPV6 networking/dns resolution to be able to say.

Appreciate any advice you guys have!

**Comment by znerol** [comment]
The `target` url parameter takes a name or an IP address, not an URL. The correct URL for your tests when running the container from your laptop would be `http://127.0.0.1:9221/pve?target=<my-domain-name-rewrite>` instead of `http://127.0.0.1:9221/pve?target=https://<my-domain-name-rewrite>`.

**Comment by wattsap** [comment]
@znerol thanks for looking into it! I thought I had tried that as well, just spun a new pod in a test namespace to test with and can confirm I am getting the same error

**Comment by wattsap** [comment]
@znerol good idea

results using dns name:
`kubectl run tmp-shell -n test --restart=Never --rm -i --tty --image curlimages/curl -- https://<my-domain-name-rewrite>:8006/
curl: (6) Could not resolve host: <my-domain-name-rewrite>
pod "tmp-shell" deleted
pod test/tmp-shell terminated (Error)`

results using IP address instead:

`kubectl run tmp-shell -n test --restart=Never --rm -i --tty --image curlimages/curl -- 192.168.1.65:8006/                          
curl: (52) Empty reply from server
pod "tmp-shell" deleted
pod test/tmp-shell terminated (Error)`

that would imply the issue is outside pve-exporter since IP address directly got empty reply, which leaves either resolution with kubernetes coredns, resolution on the DNS server, or the proxmox IPV6 implementation.

I know its outside the scope of pve-exporter, but are you aware of anything related to the setup of proxmox wrt IPV6 that would be relevant here?

**Comment by davinkevin** [comment]
@wattsap What was the solution? I have the same issue at the moment (pve in a cluster, adguard…)
