### ISSUE TITLE
Proxmox Monitoring.

### ISSUE THREAD

**Issue by mcooperRPI** [prometheus-pve/prometheus-pve-exporter#142]
Hello Everyone,

this line: python3 -m pip install prometheus-pve-exporter
      
Where is this suppose to be installed?  On the Proxmox Node/Host or the Prometheus Server?

Thanks,

**Comment by znerol** [comment]
Depends a lot how you like to deploy. Please see the wiki for detailed steps on one way to set this up:

* [PVE Exporter on Proxmox VE Node in a venv](../wiki/PVE-Exporter-on-Proxmox-VE-Node-in-a-venv)
