### ISSUE TITLE
issue not found pve_exporter.cli

### ISSUE THREAD

**Issue by shaylami** [prometheus-pve/prometheus-pve-exporter#157]
Hi i am getting an error from reding pve_exporter.cli to main
any solution
Traceback (most recent call last):
Aug 02 16:05:08 host pve_exporter[3827475]:   File "/usr/local/bin/pve_exporter", line 5, in <module>
Aug 02 16:05:08 host pve_exporter[3827475]:     from pve_exporter.cli import main
Aug 02 16:05:08 host pve_exporter[3827475]: ModuleNotFoundError: No module named 'pve_exporter'
Aug 02 16:05:08 host systemd[1]: prometheus-pve-exporter.service: Main process exited, code=exited, status=1/FAILURE

**Comment by znerol** [comment]
This looks like `pve_exporter` is not (or not properly) installed. This can also happen after a system upgrade (e.g., PVE 7 to PVE 8).

Please reinstall `pve_exporter`.

**Comment by shaylami** [comment]
its started after upgrade from 7 to 8 
i will try to remove and install again
thanks
