### ISSUE TITLE
service pve_exporter listening only on localhost

### ISSUE THREAD

**Issue by hafx** [prometheus-pve/prometheus-pve-exporter#167]
Hi, 

I'm using a specific machine to monitor my cluster proxmox. 

It means pve_exporter is on another machine.
I would like to know if it is possible to make the service listening only on socket localhost:9221 and not 0.0.0.0:9221 ?

```
[Unit]
Description=Proxmox VE Prometheus Exporter
After=network.target
Wants=network.target

[Service]
Restart=on-failure
WorkingDirectory=/usr/share/pve_exporter
ExecStart=/opt/pve-exporter/venv/bin/pve_exporter /usr/share/pve_exporter/pve_exporter.yml 9221 localhost

[Install]
WantedBy=multi-user.target`
```

Example of my systemd file. 
The "9221 localhost" doesn't make what I expected. 

Any idea ?
Thx

**Comment by znerol** [comment]
Thanks for filing this issue. Unfortunately, I cannot reproduce the problem. In my case the `pve_exporter` process correctly binds to `localhost`:

```
$ ./.venv/bin/pve_exporter pve.yml 9221 localhost
[2023-09-24 11:56:49 +0200] [2799] [INFO] Starting gunicorn 21.2.0
[2023-09-24 11:56:49 +0200] [2799] [INFO] Listening at: http://127.0.0.1:9221 (2799)
[2023-09-24 11:56:49 +0200] [2799] [INFO] Using worker: gthread
[2023-09-24 11:56:49 +0200] [2800] [INFO] Booting worker with pid: 2800
```

```
$ lsof -c pve_exporter | grep IP
pve_expor 2799   lo    5u     IPv4  26562      0t0      TCP localhost:9221 (LISTEN)
pve_expor 2800   lo    5u     IPv4  26562      0t0      TCP localhost:9221 (LISTEN)
```

Would you mind describing in more detail what you are trying, what you are expecting and what you are seeing instead?

**Comment by hafx** [comment]
Hello, 
Thanks for your answer.

I made a mistake in my config. I was editing the wrong systemd file. 
That explains why my modifications didn't take effect... 

All is working as expected now, sorry for my mistake. 
![image](https://github.com/prometheus-pve/prometheus-pve-exporter/assets/36624181/40289221-983f-4300-b279-3366895635e9)

**Comment by hafx** [comment]
Mistake from my side : edited the wrong file
