### ISSUE TITLE
No such file or directory: 'pve.yml'

### ISSUE THREAD

**Issue by Dan-Sun** [prometheus-pve/prometheus-pve-exporter#168]
Hi

I have posted actually that [here](https://github.com/prometheus-pve/prometheus-pve-exporter/issues/110#issuecomment-1731277030) too but I thought might be better to create a new issue instead.

Just testing your exporter but I can't get it to work as well.

It can't find the config file.

`docker run --name prometheus-pve-exporter -d -p 0.0.0.0:9221:9221 -v /etc/prometheus/pve.yml:/etc/pve.yml --rm prompve/prometheus-pve-exporter`

`docker run -it --rm prompve/prometheus-pve-exporter --collector.status`
```
Traceback (most recent call last):
  File "/usr/bin/pve_exporter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/pve_exporter/cli.py", line 109, in main
    with open(params.config) as handle:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'pve.yml'
```

Edit:
The config file `/etc/prometheus/pve.yml` is there.

**Comment by znerol** [comment]
Looks like the documentation is a bit vague in this regard. Please try to specify the path to the config file as the first positional argument after the image name. E.g.:

```
docker run --name prometheus-pve-exporter -d -p 0.0.0.0:9221:9221 -v /etc/prometheus/pve.yml:/etc/pve.yml --rm prompve/prometheus-pve-exporter /etc/pve.yml
```

**Comment by Dan-Sun** [comment]
Still the same issue. 

I tried another folder with 777 permissions. Same issue as well.

**Comment by Dan-Sun** [comment]
I tried the docker compose file from the pull request, but everything I do gives me the same error.

```
proxmox  | Traceback (most recent call last):
proxmox  |   File "/usr/bin/pve_exporter", line 8, in <module>
proxmox  |     sys.exit(main())
proxmox  |              ^^^^^^
proxmox  |   File "/usr/lib/python3.11/site-packages/pve_exporter/cli.py", line 109, in main
proxmox  |     with open(params.config) as handle:
proxmox  |          ^^^^^^^^^^^^^^^^^^^
proxmox  | FileNotFoundError: [Errno 2] No such file or directory: '/etc/pve.yml'
proxmox exited with code 0
```

```
    # Load configuration.
    if 'PVE_USER' in os.environ:
        config = config_from_env(os.environ)
    else:
        with open(params.config) as handle:
            config = config_from_yaml(yaml.safe_load(handle))
```

Any other ideas?

**Comment by Dan-Sun** [comment]
Finally!
It was just a permission issue for the `pve.yml` file ...
