### ISSUE TITLE
Anyone have grafana dashboards?

### ISSUE THREAD

**Issue by iHile** [prometheus-pve/prometheus-pve-exporter#19]
Hi, anybody draw it for grafana?

**Comment by rssfed23** [comment]
This would be much appreciated - got the exporter working but really struggling with the grafana side! - Anyone willing to share a dashboard will get uber kudos/karma!

**Comment by LizardM4** [comment]
I made one, you can pick it up here: https://grafana.com/dashboards/10347

I just started using it, so I don't know yet how effective it is.  
The major downside for me is labeling by id instead of name, but I couldn't find a way to work around the problem except modifying the exporter.

**Comment by znerol** [comment]
Thanks a lot for sharing @LizardM4 . I think it should be possible to join the machine metrics (cpu, mem, etc.) with info metrics (name, version, ...) as detailed in [robust perception blog](https://www.robustperception.io/exposing-the-software-version-to-prometheus).

**Comment by LizardM4** [comment]
Thank you @znerol , I've been trying to do that for quite a bit, I was even preparing a PR :D I'll update the dashboard.

**Comment by znerol** [comment]
Thanks a lot. I linked to your dashboard from the README.

**Comment by znerol** [comment]
@LizardM4 I moved the `prometheus-pve-exporter` repo into a dedicated org (#36). Would you mind updating the URL on the grafana dashboard description?

**Comment by LizardM4** [comment]
@znerol sure, done!

**Comment by znerol** [comment]
Thanks.

**Comment by shinebayar-g** [comment]
@LizardM4 does your dashboard has repo as well?

**Comment by LizardM4** [comment]
@shinebayar-g currently no (there was no need so far), but I could set up something if you have contributions.

**Comment by znerol** [comment]
@LizardM4 just drop me a line if you like to join `prometheus-pve` org on github and set up the repo there.
