### ISSUE TITLE
Add template information

### ISSUE THREAD

**Issue by rpelissi** [prometheus-pve/prometheus-pve-exporter#199]
Hi!
First thanks for this beautiful exporter :)
Could you try to add the fact that a vm is in fact a template in the pve_guest_info metric?
could be useful for filters and alerts.
Let me know if you have any question.
Thanks!

**Comment by znerol** [comment]
That might be possible. While the official docs on the [/cluster/resources](https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/resources) endpoint do not mention it, there seems to be a `template` key on returned qemu records.

Running `pvesh` against `/cluster/resources` of my cluster indicates that:
```
# pvesh get /cluster/resources --output-format json-pretty
...
[
...
  {
     ...
     "id" : "qemu/XXXX",
     "status" : "stopped",
     "template" : 1,
     "type" : "qemu",
     "uptime" : 0,
     "vmid" : XXXX
     ...
  },
...
]
```

Thus, the `template` label can likely be added from within the [ClusterResourceCollector](https://github.com/prometheus-pve/prometheus-pve-exporter/blob/117b272c0a88376650d6b362cac03142edf2c3cd/src/pve_exporter/collector/cluster.py#L147).

Pull requests welcome.

**Comment by znerol** [comment]
Thanks @spearcrow. Rolled a new release including PR #208.
