### ISSUE TITLE
Prometheus config error

### ISSUE THREAD

**Issue by Dravelz-21** [prometheus-pve/prometheus-pve-exporter#201]
Hi, I'm trying to set up the exporter the endpoint works but Prometheus fails to validate the config file.

Prometheus logs:

> ts=2023-11-24T09:02:43.625Z caller=main.go:487 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="parsing YAML file /etc/prometheus/prometheus.yml: yaml: unmarshal errors:\n  line 24: cannot unmarshal !!int `1` into []string\n  line 25: cannot unmarshal !!int `1` into []string"

Prometheus config:
![Screenshot_20231124_100745](https://github.com/prometheus-pve/prometheus-pve-exporter/assets/60406248/d9ac51dc-705a-43b4-a9ad-1ad8ee97e3bb)

**Comment by znerol** [comment]
Thanks for the report. Looks like i committed invalid examples.

Please try to put single quotes around the `cluster` and `node` values:

```
        cluster: '1'
        node: '1'
```

**Comment by Dravelz-21** [comment]
same error 

> ts=2023-11-24T09:52:18.709Z caller=main.go:487 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="parsing YAML file /etc/prometheus/prometheus.yml: yaml: unmarshal errors:\n  line 22: cannot unmarshal !!str `1` into []string\n  line 23: cannot unmarshal !!str `1` into []string"

![Screenshot_20231124_105413](https://github.com/prometheus-pve/prometheus-pve-exporter/assets/60406248/0609995f-679c-4fc7-9385-5ab4d3aeb5b0)

**Comment by znerol** [comment]
My bad, it needs to be a list. Try this:

```
        cluster: ['1']
        node: ['1']
```

**Comment by Dravelz-21** [comment]
making it a list fixed the config error but the url that prometheus tries to scrape is not valid and returns a 500 error.

the url looks like this: `http://10.0.0.10:9221/pve?cluster=1&module=default&node=1`

**Comment by Dravelz-21** [comment]
okay I fixed it this is my final config and it works like this, I'm very new to this whole database stuff so I don't know if this is right or not.

this is my working config:
![final](https://github.com/prometheus-pve/prometheus-pve-exporter/assets/60406248/31bf2893-3aaa-4703-b090-eadda476546c)

which returns this url: `http://10.0.0.10:9221/pve?cluster=1&node=1&target=10.0.0.10`
