### ISSUE TITLE
Technical limitations to running this exporter remotely from the proxmox nodes

### ISSUE THREAD

**Issue by Starttoaster** [prometheus-pve/prometheus-pve-exporter#233]
Are there any technical limitations from running this in, say, a virtual machine running on top of, or completely separately from, the proxmox cluster it's exporting metrics from? As far as I can tell, this exporter assumes it's being run on a Proxmox VE host, but it just collects metrics from an HTTP API that Proxmox exposes.

My goal would be to run this in the same k8s cluster VMs I run on top of Proxmox, rather than install this directly on my Proxmox hosts as a separate bespoke thing.

**Comment by Starttoaster** [comment]
Furthering the same goal, is there any appetite for say, a helm chart to install this in a kubernetes cluster environment?

**Comment by znerol** [comment]
> Are there any technical limitations from running this in, say, a virtual machine running on top of, or completely separately from, the proxmox cluster it's exporting metrics from

No limitations. Running prometheus-pve-exporter in its own container/pod is certainly supported.

People who like to contribute their deployments scripts are free to do so. Please start with your own repo. For a start we can link to that from the readme.
