### ISSUE TITLE
Collect node info for disk activity and network

### ISSUE THREAD

**Issue by d-uzlov** [prometheus-pve/prometheus-pve-exporter#257]
Currently metrics like `pve_disk_size_bytes`, `pve_memory_size_bytes`, `pve_cpu_usage_ratio` report values both for VMs and for nodes.

But `pve_network_transmit_bytes` and `pve_disk_write_bytes` do not have values for nodes.
Also, in the proxmox UI there is the `IO Delay` metric for the node, which is sometimes invaluable.

Would it be possible to include these metrics?

**Comment by znerol** [comment]
This exporter relies on the values reported by the [PVE API](https://pve.proxmox.com/pve-docs/api-viewer/#/cluster). Some node metrics are not available through the API. Please use [node_exporter](https://github.com/prometheus/node_exporter/) for those.

**Comment by d-uzlov** [comment]
Hi, @znerol 
I explored the PVE API a bit, and I see that it doesn't expose network and disk bytes metrics.
However, `IO Delay` seems to be available under `/nodes/{node}/status` as `data.wait`. Looks like node status is largely undocumented for some reason, but when I query my cluster, the metric is there, as well as a bunch of other stuff.

Can it become a part of `node=1` metrics?

**Comment by d-uzlov** [comment]
It seems like extended info is only available when querying the HTTP API endpoint.
`pvesh` shows very limited info.
