### ISSUE TITLE
Config option miissing on wiki page "PVE Exporter on Proxmox VE Node in a venv"

### ISSUE THREAD

**Issue by Ryan-DL** [prometheus-pve/prometheus-pve-exporter#261]
In the process of setting this up for myself, I think I noticed an issue on the wiki.

https://github.com/prometheus-pve/prometheus-pve-exporter/wiki/PVE-Exporter-on-Proxmox-VE-Node-in-a-venv#start-on-boot-up

On the systemd script, we seem to be missing the `--config.file`, leading to the service failing to start.
This line:
```
ExecStart=/opt/prometheus-pve-exporter/bin/pve_exporter /etc/prometheus/pve.yml
```
should be changed to:
```
ExecStart=/opt/prometheus-pve-exporter/bin/pve_exporter --config.file /etc/prometheus/pve.yml
```

I would happily PR this but it seems GitHub doesn't support pull requests on Wiki documents.

**Comment by znerol** [comment]
Thanks for the report, fixed it.
