### ISSUE TITLE
Missing metrics

### ISSUE THREAD

**Issue by vaclavku** [prometheus-pve/prometheus-pve-exporter#265]
Hello, I installed prometheus-pve-exporter in docker and enabled to scrape the PVE metrics. (I'm using version 8.2.4.).
My issue is that I receive just your internal metrics and not the PVE relevant. 
Any advice/hint?
Many thanks,
Vaclav

# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 1.103518e+06
python_gc_objects_collected_total{generation="1"} 288297.0
python_gc_objects_collected_total{generation="2"} 20598.0
# HELP python_gc_objects_uncollectable_total Uncollectable objects found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 1834.0
python_gc_collections_total{generation="1"} 166.0
python_gc_collections_total{generation="2"} 5.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="12",patchlevel="3",version="3.12.3"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 4.4347392e+07
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 3.2395264e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.72052305563e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 30.87
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 13.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP pve_collection_duration_seconds Duration of collections by the PVE exporter
# TYPE pve_collection_duration_seconds summary
pve_collection_duration_seconds_count{module="default"} 0.0
pve_collection_duration_seconds_sum{module="default"} 0.0
# HELP pve_collection_duration_seconds_created Duration of collections by the PVE exporter
# TYPE pve_collection_duration_seconds_created gauge
pve_collection_duration_seconds_created{module="default"} 1.7205230564812522e+09
# HELP pve_request_errors_total Errors in requests to PVE exporter
# TYPE pve_request_errors_total counter
pve_request_errors_total{module="default"} 91.0
# HELP pve_request_errors_created Errors in requests to PVE exporter
# TYPE pve_request_errors_created gauge
pve_request_errors_created{module="default"} 1.7205230564812417e+09

**Comment by vaclavku** [comment]
It was an issue of misconfiguration. I didn't carefully follow the manual.

**Comment by yanne057** [comment]
How did you solve it i couldn't find anything wrong when looking at my config and the manual?

**Comment by vaclavku** [comment]
Hi, my docker-compose was wrong and I didn't call the logs correctly. I had
multiple issues as I run prometheus on the separate device.

út 27. 8. 2024 v 18:26 odesílatel yanne057 ***@***.***>
napsal:
