### ISSUE TITLE
verify_ssl Invalid for Let's Encrypt SSL 

### ISSUE THREAD

**Issue by lslvxy** [prometheus-pve/prometheus-pve-exporter#270]
I used Let's Encrypt signed certificates,but when i set verify_ssl to false
It still display l SSLError
<img width="1254" alt="image" src="https://github.com/user-attachments/assets/da62b9f7-1f41-4449-b672-780b7a961ca9">
i have tried  https://192.168.50.177:9221/pve?target=10.10.10.127 or http://192.168.50.177:9221/pve?target=10.10.10.127
all the same SSLError
start command is 
```
/root/python/bin/pve_exporter --config.file=/etc/prometheus/pve.yml  --server.keyfile=/etc/pve/local/pve-ssl.key --server.certfile=/etc/pve/local/pve-ssl.pem
```

**Comment by znerol** [comment]
Do not use an IP address as `target`, use the FQDN.
