### ISSUE TITLE
Getting more host metrics

### ISSUE THREAD

**Issue by YLnelson** [prometheus-pve/prometheus-pve-exporter#279]
Hi there, does exporter exposes host I/O delay & swap usage metrics?
Because it seems like these metrics are available at `/api2/json/nodes/{node_name}/status`. Thanks!

**Comment by arahard** [comment]
i agree with that ! :)

**Comment by firesalp** [comment]
Hi YLnelson, this make perfect sense ! I hope this will come soon

**Comment by znerol** [comment]
Please use node_exporter:https://github.com/prometheus/node_exporter/ to get those.
