### ISSUE TITLE
Get guest name and tags in disk_size and pve_up metrics

### ISSUE THREAD

**Issue by kevin-snt** [prometheus-pve/prometheus-pve-exporter#280]
It will be great for alerting rule to have name and tags in metrics other than guest info to make more accurate query on alerting

Thanks

**Comment by znerol** [comment]
Please use the power of PromQL to get those labels from the `pve_guest_info` metric. An example can be found in this comment (and the blog linked from there): https://github.com/prometheus-pve/prometheus-pve-exporter/issues/204#issuecomment-1835854976
