### ISSUE TITLE
pve_guest_info is bugged

### ISSUE THREAD

**Issue by sTiKyt** [prometheus-pve/prometheus-pve-exporter#290]
After restoring VM 333 from a backup on my proxmox server, over the previous one, here's the data i'm getting:

![image](https://github.com/user-attachments/assets/2a8e87d5-c6aa-4379-994e-1982f6b3dc74)

How the hell do i filter it out - i have no idea, this is the only place i could get guest's name and node, and i can't filter it out by ID because it's literally reusing an existing one

Here's the query that was working great for me, before i've found this bug:
`pve_up * on(id) group_left(node, name) pve_guest_info{id=~"(qemu|lxc)/.+"}`

I had alerts based on this, but now the data it provides in useless, as my alerts are screaming at me now

**Comment by znerol** [comment]
This is not an exporter question. See <a href="https://stackoverflow.com/a/49859361">this SO answer</a> for one way on how to drop spurious time series.

**Comment by znerol** [comment]
Official prometheus docs [here](https://prometheus.io/docs/prometheus/latest/querying/api/#delete-series).

**Comment by sTiKyt** [comment]
> This is not an exporter question. See [this SO answer](https://stackoverflow.com/a/49859361) for one way on how to drop spurious time series.

But it would re-appear every time i restore the backup, no?
