### ISSUE TITLE
Cpu usage not working like explained in the readme.

### ISSUE THREAD

**Issue by hugosxm** [prometheus-pve/prometheus-pve-exporter#292]
Hi, 

I have a 48CPU node, and it shows that in the exporter metrics :
`pve_cpu_usage_limit{id="node/vc1"} 48.0`

But if I stress the cpu with the stress commande, I have 25% in the proxmox webui and : 

`pve_cpu_usage_ratio{id="node/vc1"} 0.255540285174369`

But the doc says : 

`# HELP pve_cpu_usage_ratio CPU usage (value between 0.0 and pve_cpu_usage_limit)`

I am on pve 8.1.10.

So I think the truth is that the metric is just a "classic" percentage going from 0 to 1 and not from 0 to pve_cpu_usage_limit. If someone can confirm that ? 

Thanks

**Comment by znerol** [comment]
Yes, I guess that the docs are wrong. A more accurate explanation is given on the [API docs page](https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/resources).

* `cpu`: CPU utilization (when type in node,qemu,lxc).
* `maxcpu`: Number of available CPUs (when type in node,qemu,lxc).

We should probably just use the upstream descriptions. PR welcome.
