### ISSUE TITLE
Support for basic_auth_users and tls_server_config in pve_exporter

### ISSUE THREAD

**Issue by kbaniszack** [prometheus-pve/prometheus-pve-exporter#298]
Hello,

I have a couple of questions regarding the pve_exporter:

Does pve_exporter support the basic_auth_users configuration like other Prometheus exporters? I couldn't find any documentation or mention of it, and it seems unavailable in the current version.
Is tls_server_config fully supported? I tried configuring it, but it didn't seem to have any effect.

Context:
From my understanding, many Prometheus exporters implement these features via the Exporter Toolkit. Does pve_exporter rely on this toolkit, or is there another reason these features might not work as expected?

Thanks in advance

**Comment by znerol** [comment]
`pve_exporter` is written in `python`. Thus, it cannot reuse the Exporter Toolkit which is written in `go`. Authentication needs to be implemented in a reverse proxy at this time.

**Comment by kbaniszack** [comment]
Thank you.
Do you think it's possible to implement basic_auth_users in the module directly instead of having to do it in a reverse proxy?
I might eventually look into doing the implementation if it is possible and interesting.
