### ISSUE TITLE
Error after cluster Construction 

### ISSUE THREAD

**Issue by smilebasti** [prometheus-pve/prometheus-pve-exporter#34]
Hi, 
i had everything running on me server but as i added the first other server to form a cluster it has brocken. (not high available).
Under the domain http://192.168.20.55:9221/pve?target=192.168.20.5 i am seeing this error: 595 Errors during connection establishment, proxy handshake: No route to host -

The second server is not running when i get this error.
If i turn both on it works expect the host cpu an host memory with error: Only queries that return single series/table is supported.
What also could be why it is not showing because the turned off server is called 1 and is listed above the main server called 3.

Thanks for any ideas how to solve my problem of monitoring if on server is turned off and maybe also how to monitor all cpus.

**Comment by znerol** [comment]
In the URL above I see two different IP addresses: 192.168.20.55 and 192.168.20.5

Is this a copy&paste error or did you specify different IPs on purpose?

**Comment by smilebasti** [comment]
I am running this in a vm .55 and the proxmox host is .5. no Error.
When both servers are running i am getting no errors

**Comment by znerol** [comment]
Could you please post the stack trace of prometheus-pve-exporter which is produced in the logs when the error occures? You find the logs either directly on the console (if you start pve exporter manually) or using `journalctl -u prometheus-pve-exporter.service` if you did setup a systemd unit.

**Comment by smilebasti** [comment]
This is the output about every 15 seconds: "GET /pve?module=default&target=192.168.20.5 HTTP/1.1" 500 -

I also tried to add another node and it worked when all 3 were running. But the same here i i power down one node it stops working

**Comment by znerol** [comment]
A stack trace looks something like this:

```
Exception thrown while rendering view
Traceback (most recent call last):
  File "/home/lo/Documents/prj/prometheus-pve-exporter/src/pve_exporter/http.py", line 103, in view
    return self._views[endpoint](**params)
  File "/home/lo/Documents/prj/prometheus-pve-exporter/src/pve_exporter/http.py", line 55, in on_pve
    output = collect_pve(self._config[module], target)
  File "/home/lo/Documents/prj/prometheus-pve-exporter/src/pve_exporter/collector.py", line 291, in collect_pve
    pve = ProxmoxAPI(host, **config)
TypeError: type object argument after ** must be a mapping, not NoneType
127.0.0.1 - - [02/May/2020 17:23:28] "GET /pve?module=default HTTP/1.1" 500 -
```

Do you see something which looks like the above in your logs? If you don't, then please update to the very latest version of `prometheus-pve-exporter`:

```
pip install --upgrade prometheus-pve-exporter
```

**Comment by smilebasti** [comment]
this is the output of: journalctl -u prometheus-pve-exporter.service 
![image](https://user-images.githubusercontent.com/60941345/83358545-933cf180-a374-11ea-9ae2-fd805d38137a.png)

The output still looks the same after the upgrade Command

**Comment by znerol** [comment]
After the update you need to restart the service (`systemctl restart prometheus-pve-exporter`)

**Comment by smilebasti** [comment]
![image](https://user-images.githubusercontent.com/60941345/83739115-7561dc00-a655-11ea-8c8b-1c8eddd1c13d.png)
![image](https://user-images.githubusercontent.com/60941345/83739166-86aae880-a655-11ea-8a4a-af6ca9b62a94.png)

**Comment by smilebasti** [comment]
i am also sometimes getting this
![image](https://user-images.githubusercontent.com/60941345/83740378-0ab1a000-a657-11ea-8bff-a82090924b38.png)

**Comment by znerol** [comment]
Can you ping the target (PVE) when you are logged into the grafana machine?

```
ping -c3 192.168.20.5
```

**Comment by smilebasti** [comment]
.5 is the main Server which is always online.

**Comment by smilebasti** [comment]
I have retried to ping the server and now it works but the Grafana Panel is still not showing when one node is down

**Comment by znerol** [comment]
Closing this. Please open a new issue if this problem is still present with `2.0.1`.

**Comment by C-Duv** [comment]
To help anyone finding this issue: I had "401 Unauthorized: invalid token value!" in the exporter logs errors right after created a Proxmox cluster, for all nodes, except for the one from which I had created the cluster.

Because, before cluster creation, all my nodes were using the same generic user name for the exporter (a simple `pve_exporter@pve`) and when Promox created the cluster it kept only one.

Solution was to set the token to the only remaining one on all hosts/nodes.
