### ISSUE TITLE
Use tokens for PVE authentication

### ISSUE THREAD

**Issue by sshaikh** [prometheus-pve/prometheus-pve-exporter#43]
Allow the use of API tokens for authentication instead of username and password.

**Comment by znerol** [comment]
In principle this should be supported out of the box since the config is passed directly to [ProxmoxAPI](https://pypi.org/project/proxmoxer/#short-usage-information). Please try the following config:

```
default:
  user: "..."
  token_name: "..."
  token_value: "..."

**Comment by sshaikh** [comment]
Makes sense - and yes your suggestion worked perfectly. Thanks for the tool!

**Comment by znerol** [comment]
Cool, thanks for letting me know. I'll add that to the readme.

**Comment by sshaikh** [comment]
Looks good - although I think you'd still require "verify_ssl: false" as appropriate.

**Comment by znerol** [comment]
True. However, I'd like to nudge people away from just slapping on `verify_ssl` and towards using proper certs. Thus added a note about that.
