### ISSUE TITLE
Examples: pve-exporter using dns_sd_configs

### ISSUE THREAD

**Issue by jessechahal** [prometheus-pve/prometheus-pve-exporter#53]
Hi, 

I was wondering if it was possible to add a few examples to the documentation to include pve-exporter running on prometheus host and trying to reach proxmox using `dns_sd_configs:` section.

**Comment by znerol** [comment]
Regrettably I cannot help with that here. I suggest that you first figure out a working config using `static_configs` and then try to migrate that to `dns_sd_configs`. If you get into trouble during that process,  then ask specific questions in one of the [prometheus community](https://prometheus.io/community/) channels.
