### ISSUE TITLE
timeout issues

### ISSUE THREAD

**Issue by remyd1** [prometheus-pve/prometheus-pve-exporter#66]
Hi,

I am getting timeout errors while trying to get informations. I think I know where this error come from, but first, I would like to handle this problem properly.

Bellow the output of `journalctl` on this service:

```
Mar 30 11:59:18 node03 pve_exporter[8669]: Exception thrown while scraping quemu/lxc config from IronThrone01
Mar 30 11:59:18 node03 pve_exporter[8669]: Traceback (most recent call last):
Mar 30 11:59:18 node03 pve_exporter[8669]:   File "/opt/prometheus-pve-exporter/lib/python3.7/site-packages/pve_exporter/collector.py", line 289, in collect
Mar 30 11:59:18 node03 pve_exporter[8669]:     for vmdata in self._pve.nodes(node['node']).qemu.get():
Mar 30 11:59:18 node03 pve_exporter[8669]:   File "/opt/prometheus-pve-exporter/lib/python3.7/site-packages/proxmoxer/core.py", line 105, in get
Mar 30 11:59:18 node03 pve_exporter[8669]:     return self(args)._request("GET", params=params)
Mar 30 11:59:18 node03 pve_exporter[8669]:   File "/opt/prometheus-pve-exporter/lib/python3.7/site-packages/proxmoxer/core.py", line 94, in _request
Mar 30 11:59:18 node03 pve_exporter[8669]:     resp.reason, resp.content))
Mar 30 11:59:18 node03 pve_exporter[8669]: proxmoxer.core.ResourceException: 595 Errors during connection establishment, proxy handshake: Connection timed out - b''
```

However, I am able to retrieve manually those values:

```
time wget -O px03.html http://localhost:9221/pve?target=1.2.3.4
```

It took almost 1 minute, and px03.html seems to be a valid plain ASCII text file with keys/values.

My first idea was to increase this timeout values. Any idea if this is directly possible from the daemon ?

When I `grep` directly into the code for `timeout` values I found many references, but I do not see any global option ?

Best regards,

**Comment by znerol** [comment]
Thanks for the report. Regrettably one of the collectors is inherently inefficient (see #58 and #55 for more details). Thus I recommend to run prometheus pve exporter with the `--no-collector.config` unless you absolutely need the `pve_onboot_status` metric. If you still see timeouts or other failures, then please just reopen the issue.
