### ISSUE TITLE
Can't connect to Proxmox VE Node

### ISSUE THREAD

**Issue by 3vaLpwner** [prometheus-pve/prometheus-pve-exporter#70]
Hello everyone!
I have prometheus VM with installed pve_exporter on it.

Content of pve.yml:
default:
  user: groot
  password: Rock123!
  verify_ssl: false

Proxmox VE is set on other ip and can be opened by https://proxmox_ip:8006 with authentication above.

But when i type http://pve_exporter_ip:9221/pve?target=proxmox_ip 
it gets me an error:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Apr 16 09:50:21 prometheus pve_exporter[16507]:     raise AuthenticationError("Couldn't authenticate user: {0} to {1}".format(self.username, self.base_url + "/access/ticket"))
Apr 16 09:50:21 prometheus pve_exporter[16507]: proxmoxer.backends.https.AuthenticationError: Couldn't authenticate user: groot to https://proxmox_ip:8006/api2/json/access/ticket
Apr 16 09:50:21 prometheus pve_exporter[16507]: client_ip - - [16/Apr/2021 09:50:21] "GET /pve?target=proxmox_ip HTTP/1.1" 500 -

Any help wil be appreciated. Many thanks.

**Comment by znerol** [comment]
Please double check username and password. Is your user really named `groot`? Did you maybe misspelled `root`? Also note that it is recommended to create a dedicated user for PVE prometheus exporter.

**Comment by 3vaLpwner** [comment]
My fault, pam was allowed instead of pve. I've created prometheus user with pve auth type and it all works fine, i can see metrics!
