### ISSUE TITLE
Build fails because of missing tests

### ISSUE THREAD

**Issue by vojta001** [prometheus-pve/prometheus-pve-exporter#72]
Build with auto running tests fails with `ModuleNotFoundError: No module named 'tests'`. I suspect the following line shall be removed
https://github.com/prometheus-pve/prometheus-pve-exporter/blob/4b5b2b8c1a96858698be9fc2f8c637e1bc9c3e0c/setup.py#L21

**Comment by znerol** [comment]
Correct. We might want to start adding tests. `config.py` could be easily covered by unittests. For the classes in `collector.py` we might get away with stubbing Proxmoxer.

**Comment by vojta001** [comment]
Planning to write tests is awesome, but the current situation is a bit unfortunate as many packaging tools run tests automatically when `test_suite` is set and therefore fail.

**Comment by znerol** [comment]
Could you please point me to an example of such a packaging tool which runs tests automatically? I'd like to repro the issue before I'll attempt to fix it (in one way or the other).

**Comment by znerol** [comment]
Looked a bit into this.

* The `setup.py test` command is deprecated pypa/setuptools#1684
  Running `setup.py test` results in the following warning:
  > WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
* Distribution packaging tooling like [dh-python](https://manpages.debian.org/bullseye/dh-python/pybuild.1.en.html#TESTS) accept command line parameters for different test runners.

I conclude that removing `test_suite="tests",` as suggested by @vojta001 is correct no matter whether tests are added or not.

**Comment by znerol** [comment]
Merged #86, the fix will be part of the next release.

Thanks for taking the time to report this issue.
