### ISSUE TITLE
Curl pve metrics from endpoint

### ISSUE THREAD

**Issue by lotusnoir** [prometheus-pve/prometheus-pve-exporter#73]
hello, thanks for this exporter.

I just would like to export metrics from curl and i dont succeed, can you help ? Trying to pass login/pass or targets doesnt change the result.

```
# curl localhost:9111/pve
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>HTTPSConnectionPool(host='localhost', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x74f8f7b9c550&gt;: Failed to establish a new connection: [Errno 111] Connection refused',))</p>
```
Thanks in advance

**Comment by znerol** [comment]
Are you running `pve_exporter` on the same host as proxmox or do you run it on a different one?

**Comment by lotusnoir** [comment]
Yes I run the pve exporter on the prometheus serveur. And I scrape the data of 3 pve nodes from their URL. I tryied to pass the URL with the target parameter with no success.

**Comment by znerol** [comment]
The error `[Errno 111] Connection refused` indicates, that the PVE web interface is not reachable on port `8006` via HTTPS. Please check the following things:
* Verify that you are running an up-to-date PVE version.
* Can you access the PVE web interface on port 8006 with a browser (i.e., open `https://your-pve-node.com:8006` in your browser. also try `https://your.node.ip.address:8006/`)?

**Comment by marksugar** [comment]
```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))
```
this seems to be a certificate verification issue

**Comment by znerol** [comment]
> this seems to be a certificate verification issue

But that's a different error than the OP. @marksugar if you need help with that one, then please open a new issue.

**Comment by znerol** [comment]
Closing this, please open a new issue if necessary.
