### ISSUE TITLE
After upgrading to Proxmox 7, the pve-exporter stopped working

### ISSUE THREAD

**Issue by rogierlommers** [prometheus-pve/prometheus-pve-exporter#74]
I just upgraded to V7 of proxmox (clean install) and I want to re-install the pve-exporter.
This is what I did:

- Created os user: `useradd prometheus -M`
- Then created user in proxmox GUI as well (see screenshot below)
- Then changed password
- Then installed the pve exporter using:

```
apt-get install python3-venv
python3 -m venv /opt/prometheus-pve-exporter
cd /opt/prometheus-pve-exporter
/opt/prometheus-pve-exporter/bin/pip install prometheus-pve-exporter
```

Now when I start the pve-exporter using `/opt/prometheus-pve-exporter/bin/pve_exporter /etc/prometheus/pve.yml 9211 localhost`, it successfully binds and I can reach it. However, when trying to get the metrics, I get this error:

```
Jul 07 20:44:47 pve pve_exporter[9736]:   File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/proxmoxer/core.py", line 127, in __init__
Jul 07 20:44:47 pve pve_exporter[9736]:     self._backend = importlib.import_module('.backends.%s' % backend, 'proxmoxer').Backend(host, **kwargs)
Jul 07 20:44:47 pve pve_exporter[9736]:   File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/proxmoxer/backends/https.py", line 198, in __init__
Jul 07 20:44:47 pve pve_exporter[9736]:     self.auth = ProxmoxHTTPAuth(self.base_url, user, password, verify_ssl, timeout)
Jul 07 20:44:47 pve pve_exporter[9736]:   File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/proxmoxer/backends/https.py", line 66, in __init__
Jul 07 20:44:47 pve pve_exporter[9736]:     self._getNewTokens(password=password)
Jul 07 20:44:47 pve pve_exporter[9736]:   File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/proxmoxer/backends/https.py", line 79, in _getNewTokens
Jul 07 20:44:47 pve pve_exporter[9736]:     raise AuthenticationError("Couldn't authenticate user: {0} to {1}".format(self.username, self.base_url + "/access/ticket"))
Jul 07 20:44:47 pve pve_exporter[9736]: proxmoxer.backends.https.AuthenticationError: Couldn't authenticate user: prometheus@pve to https://localhost:8006/api2/json/access/ticket
Jul 07 20:44:47 pve pve_exporter[9736]: 127.0.0.1 - - [07/Jul/2021 20:44:47] "GET /pve HTTP/1.1" 500 -
```

<img width="873" alt="Screenshot 2021-07-07 at 20 45 06" src="https://user-images.githubusercontent.com/3907131/124812965-95548500-df64-11eb-92af-fb96e187e58a.png">

The contents of my `/etc/prometheus/pve.yml`-file is this:

```
default:
    user: prometheus@pve
    password: sEcr3T!
    verify_ssl: false
```

**Comment by znerol** [comment]
Somebody reported in https://github.com/prometheus-pve/prometheus-pve-exporter/issues/70#issuecomment-821155106 that it is necessary to set the user type to `pve` instead of `pam` (when creating the user in pve web ui).

**Comment by rogierlommers** [comment]
> Somebody reported in [#70 (comment)](https://github.com/prometheus-pve/prometheus-pve-exporter/issues/70#issuecomment-821155106) that it is necessary to set the ~user type~ realm to `pve` instead of `pam` (when creating the user in pve web ui).

Ah, that fixed it! I have updated my notes.
Will not happen again :).
