### ISSUE TITLE
500 & 403 errors in logs

### ISSUE THREAD

**Issue by jasonjgeiger** [prometheus-pve/prometheus-pve-exporter#75]
I'm hitting 500 & 403 errors when attempting to run prometheus-pve-exporter in Docker. I am having difficulty determining what is causing these errors. I confirmed the user and token details - so I'm pretty confident that it's a not copy/paste issue.

## Environment details
Proxmox
- 6.4-4

VM running
- Ubuntu 20.04.2
- Docker 20.10.2
- Docker-compose 1.25.0

## Proxmox token settings
<img width="892" alt="Screen Shot 2021-07-12 at 2 11 48 PM" src="https://user-images.githubusercontent.com/448523/125356486-1cb24780-e31b-11eb-9f2c-4c06818464f7.png">

## docker-compose.yml
```
version: "3.3"
proxmox:
    image: prompve/prometheus-pve-exporter
    container_name: prometheus-pve-exporter
    ports:
      - 9221:9221
    volumes:
      - ./proxmox/pve.yml:/etc/pve.yml
```
## pve.yml
```
default:
    user: monitor@pve
    token_name: exporter
    token_value: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    verify_ssl: false
```
## Logs
```
* Running on http://localhost:9221/ (Press CTRL+C to quit),
Exception thrown while rendering view,
Traceback (most recent call last):,
  File "/usr/lib/python3.8/site-packages/pve_exporter/http.py", line 96, in view,
    return view_registry[endpoint](**params),
  File "/usr/lib/python3.8/site-packages/pve_exporter/http.py", line 38, in on_pve,
    output = collect_pve(self._config[module], target, self._collectors),
  File "/usr/lib/python3.8/site-packages/pve_exporter/collector.py", line 332, in collect_pve,
    return generate_latest(registry),
  File "/usr/lib/python3.8/site-packages/prometheus_client/exposition.py", line 107, in generate_latest,
    for metric in registry.collect():,
  File "/usr/lib/python3.8/site-packages/prometheus_client/registry.py", line 83, in collect,
    for metric in collector.collect():,
  File "/usr/lib/python3.8/site-packages/pve_exporter/collector.py", line 45, in collect,
    for entry in self._pve.cluster.status.get():,
  File "/usr/lib/python3.8/site-packages/proxmoxer/core.py", line 105, in get,
    return self(args)._request("GET", params=params),
  File "/usr/lib/python3.8/site-packages/proxmoxer/core.py", line 90, in _request,
    raise ResourceException("{0} {1}: {2} - {3}".format(,
proxmoxer.core.ResourceException: 403 Forbidden: Permission check failed (/, Sys.Audit) - b'{"data":null}',
10.0.0.200 - - [12/Jul/2021 20:50:03] "GET /pve?module=default&target=proxmox.lan HTTP/1.1" 500 -
```

**Comment by jasonjgeiger** [comment]
API token permissions issue.

**Comment by forresthopkinsa** [comment]
This issue and #69 could both be potentially very helpful to my problem if you guys would elaborate past "token issue". Can you please document what solved your problem?

**Comment by juju4** [comment]
For reference, token AND user must have the permission. either same, either maybe a subset of user for token one.
https://forum.proxmox.com/threads/vm-403-permission-check-failed-nodes-pve2-sys-audit.113139/
https://pve.proxmox.com/pve-docs/pve-admin-guide.html#pveum_permission_management
https://forum.proxmox.com/threads/empty-api-response-when-getting-vms.80330/
https://github.com/prometheus-pve/prometheus-pve-exporter/issues/109
