### ISSUE TITLE
Looking for a Co-maintainer

### ISSUE THREAD

**Issue by znerol** [prometheus-pve/prometheus-pve-exporter#84]
Prometheus PVE Exporter has developed into a project used by people and organizations around the globe. It is a honor for me to contribute a small piece of software which makes the lives easier for fellow sysadmins and devops engineers.

At this point I can easily keep up with resolving issues and reviewing / merging PRs. In the long run it will for sure be beneficial for the project if more than one person is capable of maintaining the code base and rolling releases.

Thus, I am looking for some reliable creature who is willing to assume responsibility for the maintenance of this project and for keeping its users happy. If you are actively using Prometheus PVE Exporter, if you did contribute to this project in the past and if you like to step up as a maintainer, then please ping me (use the e-mail address on my github profile page).

**Comment by christianknell** [comment]
Are you still looking? Would love to support here.

**Comment by znerol** [comment]
Yes, I am still trying to reduce the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) on this project. Please send an e-mail to the address on my profile page. German works.

**Comment by crabhi** [comment]
Hi, I've created a fork https://github.com/monitora-media/prometheus-pve-exporter/ that I intend to maintain at least until we use it.

You may not like the changes I did - see the PRs #132, #133 and #134. If you do, I can be a co-maintainer. However, I intend to work only on bugs, security issues, upgrades and features that are important for our deployment. 🤷🏿

**Comment by znerol** [comment]
Thanks a lot for filing these PRs @crabhi I very much appreciate your efforts.

> However, I intend to work only on bugs, security issues, upgrades and features that are important for our deployment.

That is exactly my approach on software maintenance as well. And it is also the reason I was reluctant to integrate things like #133 in the past.

**Comment by crabhi** [comment]
I can totally understand that.

**Comment by resmo** [comment]
Late to the party but I would also like to join to the list of possible maintainers since I also use it and know a bit of python. And btw, have we met, have we?

**Comment by znerol** [comment]
Cool, thanks @resmo and yes, we have met a couple of times.

**Comment by znerol** [comment]
Thanks @resmo for stepping up and welcome to the project.
