### ISSUE TITLE
v2.2.0 isn't available on dockerhub

### ISSUE THREAD

**Issue by michaelarnauts** [prometheus-pve/prometheus-pve-exporter#85]
It seems v2.2.0 isn't available yet on dockerhub. I know they recently changes something that stops the automated builds if you don't have a premium account.

You still can build the image locally, and push it to the registry.

**Comment by znerol** [comment]
Yes, sorry for that. I'm tracking this in #80, I've filed an application for the Dockerhub OpenSource program. I have no idea how long it will take them to process it though. I'm gonna switch to GitHub actions if the answer is negative or if they fail to answer within the next couple of weeks.

**Comment by michaelarnauts** [comment]
Ow, I missed that issue.
