### ISSUE TITLE
Can't run pve_exporter

### ISSUE THREAD

**Issue by 1scrooge** [prometheus-pve/prometheus-pve-exporter#94]
I've install pve_exporter but can't run it
This is what I did:
- python3 -m venv /opt/prometheus-pve-exporter
- /opt/prometheus-pve-exporter/bin/pip install prometheus-pve-exporter

Then I tryed to start it: ``` /opt/prometheus-pve-exporter/bin/pve_exporter /etc/prometheus/pve.yml ``` but got an errorr:
``` 
Traceback (most recent call last):
  File "/opt/prometheus-pve-exporter/bin/pve_exporter", line 7, in <module>
    from pve_exporter.cli import main
  File "/opt/prometheus-pve-exporter/lib/python3.5/site-packages/pve_exporter/cli.py", line 40
    help += f" (default: {default})"
                                   ^
SyntaxError: invalid syntax
```
![image](https://user-images.githubusercontent.com/32951007/139679863-b6a9cb16-1db1-4eda-a118-f8f72c208fec.png)

**Comment by znerol** [comment]
Please use an up-to-date distribution with Python 3.6 or better. In Debian this would be `buster` or `bullseye`. Older distros are not supported.
