### ISSUE TITLE
Docker image fails on Raspberry Pi 4

### ISSUE THREAD

**Issue by vexance** [prometheus-pve/prometheus-pve-exporter#98]
The following error occurs when attempting to run the docker image on a Raspberry Pi 4 with Alpine 3.14, causing the container to stop:

```standard_init_linux.go:228: exec user process caused: exec format error```

I believe this is due to the Alpine version in the Dockerfile being specified as 3.13.6, which might not support ARM 64 CPU architecture.     [Alpine's Official Dockerhub Image](https://hub.docker.com/_/alpine) specifies the following tags as being supported:

```
    20210804, edge
    3.15.0-rc.4, 3.15
    3.14.3, 3.14, 3, latest
    3.13.7, 3.13
    3.12.9, 3.12
    3.11.13, 3.11
```

Updating the Dockerfile from `ARG alpine_version=3.13.6` => `ARG alpine_version=3.14.3` resolves the issue on my device.

**Comment by znerol** [comment]
Sorry for the late response. Fixed via #106
